USGS-CIDA/sparrow-ui

- src/main/webapp/css/custom.css
- src/main/webapp/index.jsp
Hid the Region Search as it is low priority until later.
Switched the placement of Data Series and Area of Interest in the Map Filter Sidebar
Also changed the footer url to no be cida vizzies url
> SPARROW UI tweaks for PO's

- src/main/webapp/index.jsp
- src/main/webapp/less/custom.less
Moved constituents to the map side bar filters, and reordered national models and regional models
> Adjustments

- src/main/webapp/index.jsp
Put constituents to upper bar and renamed regional models to Model Regions to accommodate nationa and other various models
> revert to older

- pom.xml
- src/main/webapp/index.jsp
- src/main/webapp/js/controller/AppRouter.js
- src/main/webapp/js/templates/home.html
- src/main/webapp/js/views/BaseView.js
- src/main/webapp/js/views/HomeView.js
- src/main/webapp/js/views/MapView.js
- src/test/js/specs/controller/AppRouterSpec.js
- src/test/js/specs/views/BaseViewSpec.js
- src/test/js/specs/views/HomeViewSpec.js
- src/test/resources/customJasmineConfig.txt
This does not complete the task. I have brought in Handlebars and am using requirejs.text to load templates as needed. Put the majority of the html that was in index.jsp and put it in a template, home.html. This will template will have pieces removed as we do the sub-views.
Added a BaseView which the majority of our views should extend. Right now it provides a default render which is run during initialize. Possibly we will add common functions (like routing or perhaps common dom manipulation functions) to this as needed.
Used the BaseView to create a HomeView which right now creates the MapView. Eventually other subviews will get created here.
Brought in squire to do the dependancy injection in the tests. Added tests for BaseView and HomeView.
> Add selects

- src/main/webapp/index.jsp
- src/main/webapp/js/models/SelectionModel.js
- src/main/webapp/js/templates/home.html
- src/main/webapp/js/templates/model_selection.html
- src/main/webapp/js/views/HomeView.js
- src/main/webapp/js/views/MapView.js
- src/main/webapp/js/views/SelectModelView.js
- src/main/webapp/less/custom.less
This is a start. I don't want to write tests for the new view until we are clearer how we are getting the meta data.
> Adding SelectModelView and SelectionModel

- pom.xml
- src/main/java/gov/usgs/cida/sparrow/ui/rest/data/ModelResource.java
- src/main/java/gov/usgs/cida/sparrow/ui/utilities/CacheManagerUtil.java
- src/main/resources/ehcache.xml
This will keep any client from hammering the sciencebase server
> Introduced ehcache in order to cache sciencebase responses

- src/main/webapp/less/custom.less
@mbucknell Worked like a charm! IE map now extends as its supposed to
> IE height issue 2.0

- src/main/webapp/js/utils/mapUtils.js
> Removed debugger

- src/main/webapp/js/views/MapView.js
Multiple mouseover regions still elusive
> Allow multiple regions to be selected

- pom.xml
- src/main/webapp/js/controller/AppRouter.js
- src/main/webapp/js/models/MapFilterModel.js
- src/main/webapp/js/templates/home.html
- src/main/webapp/js/templates/model_selection.html
- src/main/webapp/js/templates/nav.html
- src/main/webapp/js/views/HomeView.js
- src/main/webapp/js/views/MapFilterView.js
- src/main/webapp/js/views/MapView.js
- src/main/webapp/js/views/ModelDisplayView.js
- src/main/webapp/js/views/ModelMapView.js
- src/main/webapp/js/views/NavView.js
- src/main/webapp/js/views/SelectModelView.js
- src/main/webapp/less/custom.less
- src/test/js/specs/views/HomeViewSpec.js
- src/test/js/specs/views/MapFilterViewSpec.js
Added a new route to display the model was chosen. You can now click the Explore button and be routed to a view containing the map filter and showing the selected constituent and region in the Explore a Model section.
Had to disable the MapFilterView tests. Will need a service to return the available states, receiving water body,watershed, and data series (if this is model dependent). Also need to figure out how to get the model results layer for display on the map.
> Add ModelDisplayView

- src/main/webapp/js/utils/mapUtils.js
- src/main/webapp/js/views/MapView.js
- src/main/webapp/js/views/SelectModelView.js
Also Refactored region highlighting to be triggered from MapView
> Fix constituent resetting region selection

- src/test/js/specs/views/SelectModelViewSpec.js
> Corrected typo.

- src/main/webapp/index.jsp
removed ca_drought from the footer
> no more ca_drought in footer

- src/main/webapp/js/templates/nav.html
Save session and help buttons are hidden
> buttons begone

- src/main/webapp/js/views/MapView.js
- src/main/webapp/js/views/ModelDisplayView.js
- src/main/webapp/js/views/ModelMapView.js
Further cleanup on the remove functions for views. Need to make sure the BaseView.prototype.remove is called and views containing an openlayers map should call this.map.setTarget(null) in the view's remove function.
The Back button should work now.
> Add constituents

- src/main/webapp/js/templates/map_filter.html
Not going to be functional for awhile so being hidden
> Advanced options, group results by, and downloads hidden

- src/main/webapp/js/templates/nav.html
- src/main/webapp/less/base.less
- src/main/webapp/less/custom.less
Added hide header footer button.
Moved the region selection, model filters and the OL zoom button around to create a less oddly stacked ui experience
@isuftin want to give it a look?
> Added hide header footer button and css changes

- src/main/webapp/less/custom.less
Left aligned the region pop up text options
> left aligned pop up region options

- src/main/webapp/index.jsp
- src/main/webapp/less/custom.less
Added a new google font to modernize the apps look.
> New font for web app

- src/main/webapp/js/templates/map_filter.html
Uncommented the data series section on the map filter
> Data series is back

- src/main/webapp/js/templates/model_selection.html
- src/main/webapp/js/views/MapFilterView.js
- src/main/webapp/js/views/SelectModelView.js
Those items are informational only ("Select a ... ")
Also some JSHint fixes
> Disallowing users to select the first item in the constituent/region dropdowns

- src/main/webapp/js/utils/mapUtils.js
- src/main/webapp/js/views/MapView.js
- src/main/webapp/js/views/SelectModelView.js
Now choosing no region gets map to show all regions again. 
Selecting the first option in either dropdown will reset that selection.
> Updated functionality for model select boxes

- src/main/webapp/js/utils/mapUtils.js
- src/main/webapp/js/views/MapView.js
Now passing in a collection of vector layers instead of the map in order to abstract the function a bit
> Refactored MapUtils.highlightRegion

- src/main/webapp/js/templates/map_filter.html
- src/main/webapp/js/templates/reset.html
- src/main/webapp/less/custom.less
1.) Separated the Area of Interest and Data Series into separate boxes to distinguish difference between them.
2.) The two reset buttons now have different titles, the map reset is now Reset Map, and the filters one is Clear Filters
3.) The Area of interest area now has sub titles above each selection to explain what they are
> separation, sub titles, and resets name changes

- src/main/webapp/js/views/ModelMapView.js
Now using WITHIN OR OVERLAPS as a spatial filter
> Fix spatial filtering to properly display model results

- src/main/webapp/js/utils/spatialUtils.js
I made a few (hopefully) non-functional changes as a part of getting to know the code better.
> https://trello.com/c/SVSoZiql
